// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ndemf059mPaftHBVDFBVn-d6RGXPleU',
    appId: '1:766630085430:web:5f8d04fb4026dce22a2997',
    messagingSenderId: '766630085430',
    projectId: 'schollery-bb4df',
    authDomain: 'schollery-bb4df.firebaseapp.com',
    storageBucket: 'schollery-bb4df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtIocXKGIqGeC5oWWF7JClHPxJG7L0RbA',
    appId: '1:766630085430:android:afc7d21b05606b2b2a2997',
    messagingSenderId: '766630085430',
    projectId: 'schollery-bb4df',
    storageBucket: 'schollery-bb4df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTDt0HV3KL1b_rofyjp2RwXgAh7oEvzQ',
    appId: '1:766630085430:ios:a44c96e3057cc0262a2997',
    messagingSenderId: '766630085430',
    projectId: 'schollery-bb4df',
    storageBucket: 'schollery-bb4df.appspot.com',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTDt0HV3KL1b_rofyjp2RwXgAh7oEvzQ',
    appId: '1:766630085430:ios:45cf166d2c63ec7d2a2997',
    messagingSenderId: '766630085430',
    projectId: 'schollery-bb4df',
    storageBucket: 'schollery-bb4df.appspot.com',
    iosBundleId: 'com.example.schoolApp.RunnerTests',
  );
}
